#ifndef SCIQLOP_AMDAGLOBAL_H
#define SCIQLOP_AMDAGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(AMDA_LIB)
#define SCIQLOP_AMDA_EXPORT Q_DECL_EXPORT
#else
#define SCIQLOP_AMDA_EXPORT Q_DECL_IMPORT
#endif

#endif // SCIQLOP_AMDAGLOBAL_H
