"""Tests for SciQLop.components.workspaces.backend.workspace_project — pyproject.toml generator."""

import os
import tempfile
from pathlib import Path

import pytest

from SciQLop.components.workspaces.backend.workspace_manifest import WorkspaceManifest
from SciQLop.components.workspaces.backend.workspace_project import (
    _deduplicate_requirements,
    _slugify,
    generate_pyproject_toml,
)


class TestSlugify:
    def test_simple(self):
        assert _slugify("My Study") == "my-study"

    def test_already_slug(self):
        assert _slugify("my-study") == "my-study"

    def test_multiple_spaces_and_special_chars(self):
        assert _slugify("Hello  World! #2") == "hello--world---2"

    def test_leading_trailing_hyphens_stripped(self):
        assert _slugify("  Hello  ") == "hello"

    def test_empty_string(self):
        assert _slugify("") == ""

    def test_underscores_become_hyphens(self):
        assert _slugify("my_study") == "my-study"


class TestDeduplicateRequirements:
    def test_no_duplicates(self):
        reqs = ["speasy>=1.6", "matplotlib>=3.8"]
        result = _deduplicate_requirements(reqs)
        assert result == ["speasy>=1.6", "matplotlib>=3.8"]

    def test_duplicate_keeps_last(self):
        reqs = ["speasy>=1.0", "matplotlib>=3.8", "speasy>=1.6"]
        result = _deduplicate_requirements(reqs)
        assert result == ["matplotlib>=3.8", "speasy>=1.6"]

    def test_empty(self):
        assert _deduplicate_requirements([]) == []

    def test_case_insensitive_package_names(self):
        reqs = ["Speasy>=1.0", "speasy>=1.6"]
        result = _deduplicate_requirements(reqs)
        assert result == ["speasy>=1.6"]

    def test_extras_ignored_for_dedup(self):
        # "speasy[all]>=1.0" and "speasy>=1.6" share the same base package
        reqs = ["speasy[all]>=1.0", "speasy>=1.6"]
        result = _deduplicate_requirements(reqs)
        assert result == ["speasy>=1.6"]


class TestGeneratePyprojectToml:
    def test_basic_generation(self):
        manifest = WorkspaceManifest(
            name="My Study",
            requires=["speasy>=1.6.1"],
        )
        plugin_deps = ["matplotlib>=3.8"]

        with tempfile.TemporaryDirectory() as tmpdir:
            output = Path(tmpdir) / "pyproject.toml"
            generate_pyproject_toml(manifest, plugin_deps, output)

            content = output.read_text()
            assert "[project]" in content
            assert 'name = "sciqlop-workspace-my-study"' in content
            assert 'version = "0.0.0"' in content
            assert 'requires-python = ">=3.10"' in content
            assert '"speasy>=1.6.1"' in content
            assert '"matplotlib>=3.8"' in content
            # Should contain the auto-generated comment
            assert "Auto-generated by SciQLop" in content

    def test_empty_deps(self):
        manifest = WorkspaceManifest(name="Empty", requires=[])
        plugin_deps = []

        with tempfile.TemporaryDirectory() as tmpdir:
            output = Path(tmpdir) / "pyproject.toml"
            generate_pyproject_toml(manifest, plugin_deps, output)

            content = output.read_text()
            assert "[project]" in content
            assert 'name = "sciqlop-workspace-empty"' in content
            assert "dependencies = [\n]" in content

    def test_deduplication_across_manifest_and_plugins(self):
        manifest = WorkspaceManifest(
            name="Dedup Test",
            requires=["speasy>=1.0", "numpy>=1.24"],
        )
        # Plugin provides a newer speasy requirement
        plugin_deps = ["speasy>=1.6.1"]

        with tempfile.TemporaryDirectory() as tmpdir:
            output = Path(tmpdir) / "pyproject.toml"
            generate_pyproject_toml(manifest, plugin_deps, output)

            content = output.read_text()
            # speasy should appear only once — the plugin's version (last wins)
            assert content.count("speasy") == 1
            assert '"speasy>=1.6.1"' in content
            assert '"numpy>=1.24"' in content

    def test_output_is_valid_toml(self):
        """If tomllib is available (3.11+), verify the output parses."""
        try:
            import tomllib
        except ImportError:
            pytest.skip("tomllib not available")

        manifest = WorkspaceManifest(
            name="TOML Check",
            requires=["speasy>=1.6.1"],
        )
        plugin_deps = ["matplotlib>=3.8"]

        with tempfile.TemporaryDirectory() as tmpdir:
            output = Path(tmpdir) / "pyproject.toml"
            generate_pyproject_toml(manifest, plugin_deps, output)

            with open(output, "rb") as f:
                data = tomllib.load(f)

            assert data["project"]["name"] == "sciqlop-workspace-toml-check"
            assert data["project"]["version"] == "0.0.0"
            assert "speasy>=1.6.1" in data["project"]["dependencies"]
            assert "matplotlib>=3.8" in data["project"]["dependencies"]

    def test_accepts_path_as_string(self):
        manifest = WorkspaceManifest(name="StrPath")

        with tempfile.TemporaryDirectory() as tmpdir:
            output = os.path.join(tmpdir, "pyproject.toml")
            generate_pyproject_toml(manifest, [], output)
            assert os.path.exists(output)
