#ifndef SCIQLOP_MOCKPLUGINGLOBAL_H
#define SCIQLOP_MOCKPLUGINGLOBAL_H

#include <QtCore/QtGlobal>

#if defined(MOCKPLUGIN_LIB)
#define SCIQLOP_MOCKPLUGIN_EXPORT Q_DECL_EXPORT
#else
#define SCIQLOP_MOCKPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SCIQLOP_MOCKPLUGINGLOBAL_H
