"""Generate a pyproject.toml for a SciQLop workspace virtual environment.

The generated file merges plugin ``python_dependencies`` with workspace
``requires`` from the manifest so that ``uv sync`` can resolve them all
into one coherent environment.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import List, Sequence, Union

from SciQLop.components.workspaces.backend.workspace_manifest import WorkspaceManifest

# PEP 508 package name: letters, digits, hyphens, underscores, dots.
# We capture the base name (before any extras bracket or version specifier).
_PKG_NAME_RE = re.compile(r"^([A-Za-z0-9]([A-Za-z0-9._-]*[A-Za-z0-9])?)")


def _slugify(name: str) -> str:
    """Convert a human-readable name to a URL/package-safe slug.

    >>> _slugify("My Study")
    'my-study'
    """
    slug = name.lower()
    slug = slug.replace("_", "-")
    slug = re.sub(r"[^a-z0-9-]", "-", slug)
    slug = slug.strip("-")
    return slug


def _extract_package_name(req: str) -> str:
    """Return the normalised base package name from a PEP 508 requirement string."""
    m = _PKG_NAME_RE.match(req.strip())
    if m is None:
        return req.strip().lower()
    return m.group(1).lower().replace("_", "-").replace(".", "-")


def _deduplicate_requirements(reqs: Sequence[str]) -> List[str]:
    """De-duplicate requirements by package name, keeping the *last* occurrence."""
    seen: dict[str, int] = {}
    result: list[str] = []
    for req in reqs:
        key = _extract_package_name(req)
        if key in seen:
            # Remove the earlier entry
            result.pop(seen[key])
            # Adjust indices for entries that shifted
            seen = {k: (v if v < seen[key] else v - 1) for k, v in seen.items() if k != key}
        seen[key] = len(result)
        result.append(req)
    return result


def generate_pyproject_toml(
    manifest: WorkspaceManifest,
    plugin_deps: Sequence[str],
    output_path: Union[str, os.PathLike[str]],
) -> None:
    """Write a ``pyproject.toml`` that merges *manifest* requires and *plugin_deps*.

    Parameters
    ----------
    manifest:
        The parsed workspace manifest (must have ``name`` and ``requires``).
    plugin_deps:
        Additional Python dependency strings contributed by plugins.
    output_path:
        Filesystem path where the generated ``pyproject.toml`` will be written.
    """
    all_deps = _deduplicate_requirements(list(manifest.requires) + list(plugin_deps))
    slug = _slugify(manifest.name)

    # Format the dependencies list
    if all_deps:
        deps_lines = "\n".join(f'    "{dep}",' for dep in all_deps)
        deps_block = f"dependencies = [\n{deps_lines}\n]"
    else:
        deps_block = "dependencies = [\n]"

    content = f"""\
# Auto-generated by SciQLop launcher. Do not edit manually.
# Source of truth: workspace.sciqlop manifest

[project]
name = "sciqlop-workspace-{slug}"
version = "0.0.0"
requires-python = ">=3.10"
{deps_block}
"""

    Path(output_path).write_text(content)
