#!/usr/bin/tclsh
# This file defines the set of scripts (rules) that should be executed for a 
# default IPSIS project.

set rules {
    IPSIS_F11
    IPSIS_F13
    
    IPSIS_S01
    IPSIS_S02
    IPSIS_S03
    IPSIS_S04_FILENAME
    IPSIS_S04_NAMESPACE
    IPSIS_S04_CLASS
    IPSIS_S04_ENUM
    IPSIS_S04_TYPEDEF
    IPSIS_S04_METHOD
    IPSIS_S04_VARIABLE
    IPSIS_S05
    IPSIS_S06
    IPSIS_S09
    
    IPSIS_C01
    IPSIS_C09
    IPSIS_C11
}
