# SciQLop/sciqlop_dependencies.py - AUTO-GENERATED BY PRE-COMMIT HOOK
# DO NOT EDIT MANUALLY! Changes will be overwritten.

# This list is used at runtime for dependency checks or dynamic installation
RUNTIME_DEPENDENCIES = [
    "IPython",
    "PyGitHub",
    "PySide6-QtAds==4.4.1",
    "SciQLopPlots==0.18.0",
    "expression",
    "humanize",
    "ipykernel<7.0.0",
    "ipympl",
    "jinja2",
    "jupyterlab>=4,!=4.1.0",
    "notebook",
    "numpy",
    "platformdirs",
    "pydantic",
    "pyside6==6.9.2",
    "pyzstd",
    "qasync",
    "qtconsole",
    "scipy",
    "seaborn",
    "shiboken6==6.9.2",
    "speasy>=1.6.1"
]
