# SciQLop/sciqlop_dependencies.py - AUTO-GENERATED BY PRE-COMMIT HOOK
# DO NOT EDIT MANUALLY! Changes will be overwritten.

# This list is used at runtime for dependency checks or dynamic installation
RUNTIME_DEPENDENCIES = [
    "PyGitHub",
    "PySide6-QtAds==4.5.0.2",
    "SciQLopPlots==0.18.2",
    "expression",
    "humanize",
    "ipython==8.37.0",
    "jinja2",
    "jupyqt",
    "keyring",
    "matplotlib==3.10.3",
    "numpy",
    "platformdirs",
    "pydantic",
    "pyside6==6.10.2",
    "pyzstd",
    "qasync",
    "qtconsole",
    "scipy",
    "seaborn",
    "shiboken6==6.10.2",
    "speasy>=1.6.1",
    "tomli_w",
    "uv"
]
