#!/usr/bin/env bash
# Regenerate the Flatpak pip dependency manifest (python-deps.yaml).
# Run this after changing dependencies in pyproject.toml.
#
# Requires: pip (for downloading wheels), PyYAML

set -e
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_DIR="$SCRIPT_DIR/../.."
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

IGNORE_PKGS="pyside6 pyside6-essentials pyside6-addons shiboken6 pyside6-qtads sciqlopplots uv"

# Extract dependencies from pyproject.toml
echo "Extracting dependencies from pyproject.toml..."
DEPS=$(python3 -c "
import tomllib, pathlib
data = tomllib.loads(pathlib.Path('$REPO_DIR/pyproject.toml').read_text())
for d in data['project']['dependencies']:
    print(d)
")

echo "Downloading wheels for x86_64 / cp312..."
pip download --only-binary :all: \
    --platform manylinux_2_34_x86_64 \
    --platform manylinux_2_28_x86_64 \
    --platform manylinux_2_27_x86_64 \
    --platform manylinux_2_17_x86_64 \
    --platform manylinux2014_x86_64 \
    --platform manylinux2010_x86_64 \
    --platform linux_x86_64 \
    --python-version 312 \
    --implementation cp \
    --abi cp312 --abi abi3 \
    --dest "$TMPDIR" \
    $DEPS

echo "Generating python-deps.yaml..."
TMPDIR="$TMPDIR" SCRIPT_DIR="$SCRIPT_DIR" IGNORE_PKGS="$IGNORE_PKGS" python3 << 'PYEOF'
import hashlib, json, os, sys, urllib.request, yaml
from pathlib import Path

IGNORE = set(os.environ.get("IGNORE_PKGS", "").lower().split())
tmpdir = Path(os.environ["TMPDIR"])
output = Path(os.environ["SCRIPT_DIR"]) / "python-deps.yaml"

wheels = sorted(tmpdir.glob("*.whl"))
packages = {}
for whl in wheels:
    parts = whl.name.split("-")
    name_raw = parts[0]
    name = name_raw.lower().replace(".", "_")
    if name in IGNORE:
        continue
    version = parts[1]
    key = (name, version, name_raw)
    packages.setdefault(key, []).append(whl)

def get_pypi_url(pkg_name, version, filename):
    url = f"https://pypi.org/pypi/{pkg_name}/{version}/json"
    try:
        with urllib.request.urlopen(url) as resp:
            data = json.loads(resp.read())
            for entry in data["urls"]:
                if entry["filename"] == filename:
                    return entry["url"], entry["digests"]["sha256"]
    except Exception:
        pass
    return None, None

pip_args = []
sources = []

for i, ((name, version, name_raw), whls) in enumerate(packages.items()):
    display_name = name.replace("_", "-")
    pip_args.append(f"{display_name}=={version}")
    for whl in whls:
        local_sha = hashlib.sha256(whl.read_bytes()).hexdigest()
        url, pypi_sha = get_pypi_url(name_raw, version, whl.name)
        if url is None:
            url, pypi_sha = get_pypi_url(display_name, version, whl.name)
        if url is None:
            print(f"  WARNING: No PyPI URL for {whl.name}, skipping", file=sys.stderr)
            continue
        sha = pypi_sha or local_sha
        platform_tag = whl.name.rsplit("-", 1)[1].replace(".whl", "")
        source = {"type": "file", "url": url, "sha256": sha}
        if "x86_64" in platform_tag:
            source["only-arches"] = ["x86_64"]
        elif "aarch64" in platform_tag:
            source["only-arches"] = ["aarch64"]
        sources.append(source)
    if (i + 1) % 20 == 0:
        print(f"  Resolved {i + 1}/{len(packages)} packages...")

pip_cmd = (
    'pip3 install --verbose --no-index --no-deps --ignore-installed '
    '--find-links="file://${PWD}" --prefix=${FLATPAK_DEST} --no-build-isolation '
    + " ".join(pip_args)
)

doc = {
    "name": "python3-deps",
    "buildsystem": "simple",
    "build-commands": [pip_cmd],
    "sources": sources,
}

with open(output, "w") as f:
    f.write("# Auto-generated by update-deps.sh. Do not edit manually.\n")
    f.write("# PySide6/shiboken6/QtAds/SciQLopPlots handled in pyside6-deps.yaml\n")
    yaml.dump(doc, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

print(f"Done. {len(pip_args)} packages, {len(sources)} sources written to {output}")
PYEOF

echo ""
echo "NOTE: PySide6 deps in pyside6-deps.yaml must be updated manually"
echo "when changing PySide6/shiboken6/QtAds/SciQLopPlots versions."
