import sys
import tomllib

PYPROJECT_FILE = "pyproject.toml"
PYTHON_DEPS_FILE = "SciQLop/sciqlop_dependencies.py"
VARIABLE_NAME = "RUNTIME_DEPENDENCIES"

def extract_pyproject_deps(file_path):
    """Extracts dependencies from the [project] table in pyproject.toml."""
    try:
        with open(file_path, "rb") as f:
            data = tomllib.load(f)
        
        # Adjust this path based on where your dependencies are defined
        deps = data.get('project', {}).get('dependencies', [])
        
        # Sort and return a list of dependency strings
        return sorted(list(set(deps)))
    except FileNotFoundError:
        print(f"Error: {PYPROJECT_FILE} not found.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error parsing {PYPROJECT_FILE}: {e}", file=sys.stderr)
        sys.exit(1)

def main():
    deps = extract_pyproject_deps(PYPROJECT_FILE)
    
    # Format the content *without* writing it yet
    dep_list_str = ',\n'.join(f'    "{dep}"' for dep in deps)
    new_content = f"""# {PYTHON_DEPS_FILE} - AUTO-GENERATED BY PRE-COMMIT HOOK
# DO NOT EDIT MANUALLY! Changes will be overwritten.

# This list is used at runtime for dependency checks or dynamic installation
{VARIABLE_NAME} = [
{dep_list_str}
]
"""
    
    try:
        with open(PYTHON_DEPS_FILE, 'r') as f:
            current_content = f.read()
    except FileNotFoundError:
        current_content = "" # If file doesn't exist, current content is empty

    if current_content != new_content:
        # File needs updating: write the new content and fail the hook.
        with open(PYTHON_DEPS_FILE, 'w') as f:
            f.write(new_content)
        
        print(f"❌ {PYTHON_DEPS_FILE} was out of date and has been regenerated.")
        print("Please stage the changes in dependencies.py and re-commit.")
        sys.exit(1) # Fail the hook to force staging the generated file
    else:
        print(f"✅ {PYTHON_DEPS_FILE} is up to date.")
        sys.exit(0)

if __name__ == "__main__":
    main()
