#include "project.hpp"

#include <cctype>
#include <fstream>
#include <sstream>

namespace fs = std::filesystem;

namespace sciqlop {
namespace {

std::string slugify(const std::string& name) {
    std::string slug;
    slug.reserve(name.size());
    for (unsigned char c : name) {
        const char lowered = static_cast<char>(std::tolower(c));
        slug += (std::isalnum(c) != 0) ? lowered : '-';
    }
    const auto first = slug.find_first_not_of('-');
    if (first == std::string::npos) return "workspace";
    const auto last = slug.find_last_not_of('-');
    return slug.substr(first, last - first + 1);
}

std::string sciqlop_requirement(const std::string& version) {
    return version.empty() ? "sciqlop" : "sciqlop==" + version;
}

}  // namespace

std::string render_pyproject(const BootstrapProject& project) {
    std::ostringstream out;
    out << "# Auto-generated by the SciQLop launcher to bootstrap this workspace.\n"
           "# SciQLop rewrites this file with plugin and appstore dependencies\n"
           "# once it starts; do not edit manually.\n"
           "\n"
           "[project]\n"
        << "name = \"sciqlop-workspace-" << slugify(project.workspace_name) << "\"\n"
        << "version = \"0.0.0\"\n"
        << "requires-python = \">=" << project.python_version << "\"\n"
        << "dependencies = [\n"
        << "    \"" << sciqlop_requirement(project.sciqlop_version) << "\",\n"
        << "    \"jupyqt\",\n"
        << "]\n"
           "\n"
           "[tool.uv]\n"
           "package = false\n"
           "environments = [\n"
           "    \"sys_platform == 'linux'\",\n"
           "    \"sys_platform == 'darwin'\",\n"
           "    \"sys_platform == 'win32'\",\n"
           "]\n";
    return out.str();
}

bool write_pyproject_if_missing(const fs::path& workspace_dir, const BootstrapProject& project) {
    const fs::path path = workspace_dir / "pyproject.toml";
    std::error_code ec;
    if (fs::exists(path, ec)) return false;

    fs::create_directories(workspace_dir, ec);
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out << render_pyproject(project);
    return out.good();
}

}  // namespace sciqlop
